esphome:
  name: mini-split
  friendly_name: Mini Split AC

external_components:
  - source: /root/air/esphome/components
    components: [ airconintl ]

uart:
  tx_pin: 16
  rx_pin: 17
  baud_rate: 9600
  # debug:

climate:
  - platform: airconintl
    name: "Mini Split AC"
    temperature_unit: "C"
    compressor_frequency:
      name: "Compressor Frequency"
    compressor_frequency_setting:
      name: "Compressor Frequency Setting"
    compressor_frequency_send:
      name: "Compressor Frequency Send"
    outdoor_temperature:
      name: "Outdoor Temperature"
    outdoor_condenser_temperature:
      name: "Outdoor Condenser Temperature"
    compressor_exhaust_temperature:
      name: "Compressor Exhaust Temperature"
    target_exhaust_temperature:
      name: "Target Exhaust Temperature"
    indoor_pipe_temperature:
      name: "Indoor Evaporator Inlet Temperature"
    humidity_setpoint:
      name: "Indoor Humidity setting"
    humidity_status:
      name: "Indoor Humidity status"

switch:
  - platform: restart
    name: "AC controller restart"

esp32:
  board: wemos_d1_mini32
  framework:
    type: arduino

# Enable logging
logger:
  level: VERBOSE
  baud_rate: 0
  
# Enable Home Assistant API
api:

ota:
  - platform: esphome
web_server:
  port: 80

wifi:
  ssid: "Doma"
  password: "djivory12"

  manual_ip:
    static_ip: 10.8.10.90
    gateway: 10.8.10.1
    subnet: 255.255.255.0
    dns1: 10.8.10.1

  ap:
    ssid: "Hisense Fallback"
    password: "12345678"

captive_portal:
